### ISSUE TITLE
AddItem to Project

### ISSUE THREAD

**Issue by lutz** [dogtail9/ProjectTemplateTutorial#1]
First of all, thank you for your great tutorial. An question in context of using a custom wizard in the process of creating a project. In the  public void ProjectFinishedGenerating(Project project) of the IWizard interface i add an icon to the project and its works. fine. But in this context i try to set some attributes of the generated ProjectItem

 `public void ProjectFinishedGenerating(Project project)
        {
            try
            {
                var path = Path.Combine(Path.GetDirectoryName(project.FullName), "addon" + Path.GetExtension(_iconPath));
                File.Copy(_iconPath, path);
                project.ProjectItems.AddFromFile(path);
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.ToString());
            }
        }
`
like CopyToOutputDirectory or BuildAction. But the Properties dictionary is empty. Maybe you have an idea how i can set this attributes after adding to the project.

**Comment by dogtail9** [comment]
Hi Daniel,

You need to set the properties "BuildAction" or "CopyToOutputDirectory" on the newly created ProjectItem.

If you add a reference to VSProjLang to your Project you will find the enum VSLangProj.prjBuildAction with the possible values for the BuildAction.

I did not find an enum with the values for CopyToOutputDirectory, but i found a [post](https://stackoverflow.com/questions/23503145/why-does-the-verbiage-for-the-copy-to-output-directory-selection-change-betwee) on Stack Owerflow.

* COPYTOOUTPUTSTATE_Never = 0
* COPYTOOUTPUTSTATE_Always = 1
* COPYTOOUTPUTSTATE_PreserveNewestFile = 2

Here you can see that PreserveNewest is the only option that fits the Copy if newer UI value.

``` C#
ProjectItem newitem = project.ProjectItems.AddFromFile(imagePath);
newitem.Properties.Item("BuildAction").Value = VSLangProj.prjBuildAction.prjBuildActionEmbeddedResource;
newitem.Properties.Item("CopyToOutputDirectory").Value = 0;
```

If you use an AddTemplate method that returns null you need to get your newly created ProjectItem.

``` C#
folder.ProjectItems.AddFromTemplate(templatePath, fileName);
ProjectItem newitem = (from p in folder.ProjectItems.OfType<ProjectItem>()
                       where p.Name.Equals(fileName)
                       select p).FirstOrDefault();
```

Let me know if this helped you.
/Christer

**Comment by lutz** [comment]
Hello Christer,

thank you so much. The point was the enum 
` VSLangProj.prjBuildAction.prjBuildActionEmbeddedResource;`
After added this enum to set the attribut it works correctly. 

Best regards
Daniel
